name: xxo25
description: "Bug WhatsApp Crasher"
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  device_info_plus: ^12.3.0
  carousel_slider: ^5.1.1
  web_socket_channel: ^3.0.3
  network_info_plus: ^7.0.0
  permission_handler: ^12.0.1
  video_player: ^2.9.2
  font_awesome_flutter: ^10.7.0
  path_provider: ^2.1.1
  share_plus: ^12.0.1
  chewie: ^1.5.2
  audioplayers: ^6.5.1
  qr_flutter: ^4.1.0
  image_picker: ^1.0.4
  cached_network_image: ^3.4.1
  webview_flutter: ^4.13.1
  google_fonts: ^7.0.1
  
dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: assets/icon/icon.jpg
  image_path_ios: assets/icon/icon/icon.jpg
  image_path: assets/icon/icon.jpg
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/videos/banner.mp4
    - assets/videos/landing.mp4
    - assets/videos/splash.mp4
    - assets/images/banner.jpg

  fonts:
    - family: Orbitron
      fonts:
        - asset: fonts/Rajdhani-Regular.ttf
    - family: ShareTechMono
      fonts:
        - asset: fonts/ShareTechMono-Regular.ttf